# Generated by Django 3.1.2 on 2020-11-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('head0', models.CharField(default='', max_length=255)),
                ('chead0', models.CharField(default='', max_length=5000)),
                ('head1', models.CharField(default='', max_length=255)),
                ('chead1', models.CharField(default='', max_length=5000)),
                ('head2', models.CharField(default='', max_length=255)),
                ('chead2', models.CharField(default='', max_length=5000)),
                ('pub_data', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='shop/images/')),
            ],
        ),
    ]
